export const organizationRoles = [
  "org_owner",
  "executive",
  "merchandising_manager",
  "store_manager",
  "viewer",
] as const;

export type OrganizationRole = (typeof organizationRoles)[number];

export const permissions = [
  "organization.view",
  "organization.manage",
  "members.view",
  "members.manage",
  "audit.view",
  "location.view",
  "location.manage",
  "brand.view",
  "brand.manage",
  "onboarding.view",
  "onboarding.manage",
  "event.view",
  "data.view",
  "data.manage",
  "inventory.view",
  "inventory.manage",
  "transfer.manage",
  "stock_count.manage",
  "intelligence.run",
  "opportunity.view",
  "project.view",
  "project.manage",
  "project.approve",
  "task.view",
  "task.manage",
  "campaign_brief.view",
  "campaign_brief.manage",
  "campaign_brief.approve",
  "copilot.use",
  "integration.view",
  "integration.manage",
  "integration.sync",
  "integration.import",
] as const;

export type Permission = (typeof permissions)[number];

const rolePermissions: Record<OrganizationRole, ReadonlySet<Permission>> = {
  org_owner: new Set(permissions),
  executive: new Set([
    "organization.view",
    "members.view",
    "audit.view",
    "location.view",
    "brand.view",
    "onboarding.view",
    "event.view",
    "data.view",
    "inventory.view",
    "inventory.manage",
    "transfer.manage",
    "stock_count.manage",
    "opportunity.view",
    "project.view",
    "project.approve",
    "task.view",
    "campaign_brief.view",
    "campaign_brief.approve",
    "copilot.use",
    "integration.view",
  ]),
  merchandising_manager: new Set([
    "organization.view",
    "location.view",
    "brand.view",
    "brand.manage",
    "data.view",
    "data.manage",
    "inventory.view",
    "inventory.manage",
    "transfer.manage",
    "stock_count.manage",
    "intelligence.run",
    "opportunity.view",
    "project.view",
    "project.manage",
    "task.view",
    "task.manage",
    "campaign_brief.view",
    "campaign_brief.manage",
    "copilot.use",
    "integration.view",
    "integration.manage",
    "integration.sync",
    "integration.import",
  ]),
  store_manager: new Set([
    "organization.view",
    "location.view",
    "brand.view",
    "inventory.view",
    "inventory.manage",
    "transfer.manage",
    "stock_count.manage",
    "opportunity.view",
    "project.view",
    "task.view",
    "task.manage",
    "campaign_brief.view",
    "copilot.use",
  ]),
  viewer: new Set([
    "organization.view",
    "location.view",
    "brand.view",
    "data.view",
    "inventory.view",
    "opportunity.view",
    "project.view",
    "task.view",
    "campaign_brief.view",
    "copilot.use",
  ]),
};

export function hasPermission(
  role: OrganizationRole,
  permission: Permission,
) {
  return rolePermissions[role].has(permission);
}

export function permissionsForRole(
  role: OrganizationRole,
): ReadonlySet<Permission> {
  return rolePermissions[role];
}
